parameters:
    ksuser.user.class: KS\UserBundle\Entity\User

services:
    oauth2.user_provider:
        class: %oauth2.user_provider.class%
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@security.encoder_factory"
            - "@fos_user.user_manager"
    ksuser.handler.user:
        class: KS\UserBundle\Handler\UserHandler
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%ksuser.user.class%"
            - "@form.factory"
            -  "@ksdeal.utils.categoryoptionfield"
    ksuser.utils.usertoken:
        class: KS\UserBundle\Utils\UserTokenUtils
        arguments:
            - "@doctrine.orm.entity_manager"

    ksuser.type.user_selector:
        class: KS\UserBundle\Form\DataTransformer\UserTransformerType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: user_selector }
