parameters:
    ksuser.user.class: KS\UserBundle\Entity\User
    ksuser.userfollow.models: KS\UserBundle\Models\FollowUserManyType


services:
    ksuser.handler.userfollow:
        class: KS\DealBundle\Handler\ManyHandler
        arguments: 
            - "@doctrine.orm.entity_manager"
            - "%ksuser.user.class%"
            - "%ksuser.userfollow.models%"

    oauth2.user_provider:
        class: %oauth2.user_provider.class%
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@security.encoder_factory"
            - "@fos_user.user_manager"
    ksuser.handler.user:
        class: KS\UserBundle\Handler\UserHandler
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%ksuser.user.class%"
            - "@form.factory"
            -  "@ksdeal.utils.categoryoptionfield"
    ksuser.utils.usertoken:
        class: KS\UserBundle\Utils\UserTokenUtils
        arguments:
            - "@doctrine.orm.entity_manager"

    ksuser.type.user_selector:
        class: KS\UserBundle\Form\DataTransformer\UserTransformerType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: user_selector }
    # ksuser.listener.register:
    #     class: KS\UserBundle\Listener\RegisterListener
    #     arguments:
    #         - "@translator"
    #         - "@mailer"
    #         - "@router"
    #     tags:
    #         - { name: doctrine.event_listener, event: postPersist }
