<?php

namespace KS\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRelationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRelationRepository extends EntityRepository
{
}
