_ks_advert:
    resource: "@KSAdvertBundle/Controller/"
    type:     annotation
    prefix:   /


_ks_media:
    type:     rest
    resource: KS\MediaBundle\Controller\MediasController
    prefix: /api/public

_ks_deal:
    resource: "@KSDealBundle/Resources/config/routing.yml"
    type: rest

_ks_user:
    type:     rest
    resource: KS\UserBundle\Controller\UsersController
    prefix: /api/v1

_ks_user_public:
    type:     rest
    resource: KS\UserBundle\Controller\UsersRegisterController
    prefix: /api/public


oauth2_server:
    resource: "@OAuth2ServerBundle/Controller/"
    type:     annotation
    prefix:   /

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"