komunity_store_publicite:
    resource: "@KSPubliciteBundle/Controller/"
    type:     annotation
    prefix:   /pub

komunity_store_media:
    resource: "@KSMediaBundle/Controller/"
    type:     annotation
    prefix:   /media

komunity_store_page:
    resource: "@KSPageBundle/Controller/"
    type:     annotation
    prefix:   /


komunity_store_post:
    type:     rest
    resource: KS\PostBundle\Controller\PostsController
    prefix: /api/v1




komunity_store_user:
    type:     rest
    resource: KS\UserBundle\Controller\UsersController
    prefix: /api/v1

komunity_store_user_public:
    type:     rest
    resource: KS\UserBundle\Controller\UsersRegisterController
    prefix: /api/public

komunity_store_user_admin:
    type:     rest
    resource: KS\UserBundle\Controller\UsersAdminController
    prefix: /api/admin/v1




oauth2_server:
    resource: "@KSServerBundle/Controller/"
    type:     annotation
    prefix:   /