komunity_store_advert:
    resource: "@KSAdvertBundle/Controller/"
    type:     annotation
    prefix:   /


# komunity_store_page:
#     resource: "@KSPageBundle/Controller/"
#     type:     annotation
#     prefix:   /

komunity_store_media:
    type:     rest
    resource: KS\MediaBundle\Controller\MediasController
    prefix: /api/public

komunity_store_post:
    type:     rest
    resource: KS\DealBundle\Controller\DealsController
    prefix: /api/v1

komunity_store_user:
    type:     rest
    resource: KS\UserBundle\Controller\UsersController
    prefix: /api/v1

komunity_store_user_public:
    type:     rest
    resource: KS\UserBundle\Controller\UsersRegisterController
    prefix: /api/public

komunity_store_user_admin:
    type:     rest
    resource: KS\UserBundle\Controller\UsersAdminController
    prefix: /api/admin/v1

oauth2_server:
    resource: "@OAuth2ServerBundle/Controller/"
    type:     annotation
    prefix:   /

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"