security:
    encoders:
        KS\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        oauth2:
            id: fos_user.user_provider.username

    firewalls:
        login:
            pattern: ^/admin/login$
            anonymous: true

        main:
            pattern: ^/admin
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: /admin/login
                check_path: /admin/login_check
            logout:
                path: /admin/logout
            anonymous:    true

    access_control:
        - { path: ^/api/v1, roles: ROLE_ADMIN }
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout$, role: ROLE_USER }
        - { path: ^/admin/, role: ROLE_ADMIN }
