security:
    encoders:
        KS\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        oauth2:
            id: fos_user.user_provider.username

    firewalls:
        api:
            pattern:    ^/api/v1
            stateless:  true
            anonymous: true  
            oauth: true

        api_public:
            pattern:    ^/api/public
            stateless:  true
            anonymous: true  

        api_admin:
            pattern: ^/api/admin
            stateless: true
            anonymous: false
            oauth: true

    access_control:
        - { path: ^/api/v1, roles: ROLE_USER }

