services:
    ks.admin.deal:
        class: KS\AdminBundle\Admin\DealAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Deal, label: Deals }
        arguments: [null, KS\DealBundle\Entity\Deal, KSAdminBundle:DealAdmin]
    ks.admin.user:
        class: KS\AdminBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: User, label: Users }
        arguments: [null, KS\UserBundle\Entity\User, KSAdminBundle:UserAdmin]
    # ks.admin.userrelation:
    #     class: KS\AdminBundle\Admin\UserRelationAdmin
    #     tags:
    #         - { name: sonata.admin, manager_type: orm, group: User relation, label: Users relation }
    #     arguments: [null, KS\UserBundle\Entity\UserRelation, KSAdminBundle:UserRelationAdmin]
