services:
    ks.admin.deal:
        class: KS\AdminBundle\Admin\DealAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Deal, label: Deals }
        arguments: [null, KS\DealBundle\Entity\Deal, KSAdminBundle:DealAdmin]
