ks_deal:
    type:     rest
    resource: KS\DealBundle\Controller\DealsController
    prefix: /api/v1

ks_deal_comment:
    type:     rest
    parent: ks_deal
    resource: KS\DealBundle\Controller\CommentsController

ks_category:
    type:     rest
    resource: KS\DealBundle\Controller\CategoriesController
    prefix: /api/v1

ks_category_deal:
    type:     rest
    parent: ks_category
    resource: KS\DealBundle\Controller\CategoriesDealsController

ks_type:
    type:     rest
    resource: KS\DealBundle\Controller\TypesController
    prefix: /api/v1

ks_type_deal:
    type:     rest
    parent: ks_type
    resource: KS\DealBundle\Controller\TypesDealsController