parameters:
    ksdeal.deal.class: KS\DealBundle\Entity\Deal
    ksdeal.comment.class: KS\DealBundle\Entity\Comment
    ksdeal.commentlike.models: KS\DealBundle\Models\LikeCommentManyType
    ksdeal.deallike.models: KS\DealBundle\Models\LikeDealManyType
    ksdeal.dealshare.models: KS\DealBundle\Models\ShareDealManyType

services:
    ksdeal.utils.categoryoptionfield:
        class: KS\DealBundle\Utils\CategoryOptionField

    ksdeal.handler.deallike:
        class: KS\DealBundle\Handler\ManyHandler
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%ksdeal.deal.class%"
            - "%ksdeal.deallike.models%"

    ksdeal.handler.commentlike:
        class: KS\DealBundle\Handler\ManyHandler
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%ksdeal.comment.class%"
            - "%ksdeal.commentlike.models%"

    ksdeal.handler.sharedeal:
        class: KS\DealBundle\Handler\ManyHandler
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%ksdeal.deal.class%"
            - "%ksdeal.dealshare.models%"

    ksdeal.type.deal_selector:
        class: KS\DealBundle\Form\DataTransformer\DealTransformerType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: deal_selector }

    ksdeal.type.category_selector:
        class: KS\DealBundle\Form\DataTransformer\CategoryTransformerType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: category_selector }

    ksdeal.type.type_selector:
        class: KS\DealBundle\Form\DataTransformer\TypeTransformerType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: type_selector }

    ksdeal.handler.deal:
        class: KS\DealBundle\Handler\DealHandler
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%ksdeal.deal.class%"
            - "@form.factory"
            - "@ksdeal.utils.categoryoptionfield"

    ksdeal.handler.comment:
        class: KS\DealBundle\Handler\CommentHandler
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%ksdeal.comment.class%"
            - "@form.factory"
            - "@ksdeal.utils.categoryoptionfield"

